version: "3"
services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: digsup

  server:
    build:
      context: ./apiserver
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MAIL_HOST=mailcatcher
      - MAIL_PORT=1025
      - MAIL_USER_NAME=
      - MAIL_PASSWORD=
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=digsup
      - PG_USER=pguser
      - PG_PASSWORD=pgpassword
    depends_on:
      - mailcatcher
      - postgres

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:4000
    stdin_open: true
    depends_on:
      - server
